### ISSUE TITLE
Слоты под улучшения

### ISSUE THREAD

**Issue by Dark32** [LionZXY/SimplyHammer#11]
Добавить ограничение на накладываемые улучшения.
У молота появляется параметр вместимости улучшений, показывающий какой общий вес улучшений может быть применён к молоту.
У улучшений появляется вес, показывающий сколько место оно займёт на молоте.
Вместимость можно увеличить соеденив молот со спец улучшениями:
- кварц ада +5 вместимости за каждые 5 кварца. Но не более 50 кварца
- голова визар скелета +6 вместимосте, но не более 10 голов
- голова свинозомби +3 вместимости, но не более 10 голов
- голова игрока +10 вместимости, но не более 2 голов
- звезда ада +20 вместимости, но общая вместимость не более 400

Вместимость увеличивается на наковальне. Цена повышения вместимости выражается формулой: 5 + (номер данного улучшение вместимости)/2 + (общая вместимость)/33

**Comment by LionZXY** [comment]
Такой явный плагиат тинкера это даже для меня слишком...
