### ISSUE TITLE
Слиток меди из IC2 в OreDict "ingotSteel"

### ISSUE THREAD

**Issue by Tsyklop** [LionZXY/SimplyHammer#16]
Поставил последнюю версию мода - проблема осталась.

**Comment by LionZXY** [comment]
Fix It now

**Comment by Tsyklop** [comment]
новая версия выйдет? или пофикшено в SimplyHammers-0.9.5-BUGFIX?

**Comment by LionZXY** [comment]
Новая версия в субботу 0.9.6
