### ISSUE TITLE
Crash with SimplyHammers and Computronics

### ISSUE THREAD

**Issue by jsaggers** [LionZXY/SimplyHammer#17]
I am getting a crash between Simply Hammers and Computronics, I have started an [issue over at the Computronics Github](https://github.com/asiekierka/Computronics/issues/162)

[Pastebin](http://pastebin.com/3h7bbW2d) and the FML latest log is [here](http://www.jasonsaggers.id.au/downloads/fml-client-latest.zip)

**Comment by LionZXY** [comment]
Thanks for your problem!
