### ISSUE TITLE
[Issue] Strange OD issue

### ISSUE THREAD

**Issue by accessdenied0** [LionZXY/SimplyHammer#18]
Hello @LionZXY,

I really like your mod and I use this problem to ask you about a Enchanting support for your Hammers, because I would really love to see Silk-touch on them (an upgrade would be also awesome).

Anyway I got here because one of your hammer (the IC one) seem to mess somehow with the OD dictionary. I wanted to put steel in one of the compacter from Storage Drawers and my game crashed.
Here is the crash report: http://pastebin.com/ixq7p0xW

I'm not sure why, because the Hammer itself doesn't have a OD-entry... I going to put it maybe in the next days on the Storage Drawers Github, too, because It would be cool if they are more "bulled proof"

I thank you for your help,

access_denied

**Comment by LionZXY** [comment]
Thank you for your contribution to the development of the modification. I fix it. Changed version you can download here 
http://www.mediafire.com/download/8q1ybp9metpnbb5/SimplyHammer-0.9.6.jar
Or later (~12.12.2015) on curse
