### ISSUE TITLE
Нет текстур.

### ISSUE THREAD

**Issue by Tsyklop** [LionZXY/SimplyHammer#19]
Нет текстур у Дизасемблера и у IIEERRAA`s молота.
![2015-12-08_11 47 54](https://cloud.githubusercontent.com/assets/6783568/11652667/a0ff954e-9da1-11e5-9aff-467296874d7a.png)

**Comment by LionZXY** [comment]
Слово "WIP" не просто так. Текстурировщик занят, однако на данный момент все предметы работают стабильно. Единственно, сегодня добавлю частички дизасемблеру

**Comment by LionZXY** [comment]
P.S. Текстура EU молота исправлена. Спасибо @fewizz
