### ISSUE TITLE
Move Init to PreInit

### ISSUE THREAD

**Issue by Darkosto** [LionZXY/SimplyHammer#20]
Can you please move your initialization to proper initialization locations so mods like Hardcore Questing Mode can use your items. If not, Simply Hammers items can not be used in mods that require items being loading in preInit.

Thanks

**Comment by LionZXY** [comment]
Ok. I do it.

**Comment by LionZXY** [comment]
Remove Redston Arsenal integration and rewrite ItemInit to PreInit
http://i.imgur.com/0k32wdT.png

**Comment by Darkosto** [comment]
Thank you very much! :)
