### ISSUE TITLE
Cant get rid of hammers

### ISSUE THREAD

**Issue by Fortist** [LionZXY/SimplyHammer#21]
Like, I cant delete them from the jsons. Been trying to get rid of that rainbow hammer and the stone hammer.
But when I load my game up, they come back in the files.

**Comment by LionZXY** [comment]
Stone Hammer come back or only rainbow hammer come back?

**Comment by Fortist** [comment]
*Only the Rainbow one comes back

**Comment by LionZXY** [comment]
Ok. It will be fixed 25-28 December
