### ISSUE TITLE
Prospector's pick reports wrong ore names

### ISSUE THREAD

**Issue by Gambigobilla** [LionZXY/SimplyHammer#25]
When mod has many ores that shares same ID with different data tags prospector's pick reports found ore as the first item of the ore's ID. Because of my bad English probably i couldn't tell it any understandable way so i'll tell you with an example

ThermalFoundation:Ore:0 is Copper
ThermalFoundation:Ore:1 is Tin
ThermalFoundation:Ore:2 is Silver
ThermalFoundation:Ore:3 is Lead
ThermalFoundation:Ore:4 is Ferrous
ThermalFoundation:Ore:5 is Shiny

no matter what ore you find whether it be tin, silver, lead it always reports "Found copper ore". This is a major problem because almost every major mod uses the same system. They all store ores in one ID. This is true for Thermal Foundation, Thaumcraft, Metallurgy, Tinkers Construct.

here's a picture of the bug
http://imgur.com/tpyZEcK

**Comment by LionZXY** [comment]
Big thanks! Fix in short time!

**Comment by LionZXY** [comment]
Use last version?
