### ISSUE TITLE
Texturing changes

### ISSUE THREAD

**Issue by QuImUfu** [LionZXY/SimplyHammer#27]
I wanted to share a modification I made to make Simply Hammer support texturing better.
Those changed files make:
1. handhold Simply hammers support semi-Transparent textures:
   [HammerSimplyRender.java](https://paste.ee/p/a4PeZ)
2. all model parts with different dimensions have a different texture:
   [SimplyHammer.java](https://paste.ee/p/GVnf3)

I made an ImageMagic auto-convert script (old texture files=>new texture files) for linux, should be easily transferable to work with Windows.  
[autoconvert.sh](https://paste.ee/p/PS85Z)  

> usage:  
> $ cd /path/to/autoconvert.sh/  
> $ ./autoconvert.sh Source Destination

I converted all model textures that come with Simply Hammer and created a semi-transparent glass-like model texture for the Unstable hammer.  
[orginal-converted.zip](https://dl.dropbox.com/s/ea2xzp8xw6e7ifs/orginal-converted.zip)

**Comment by LionZXY** [comment]
Ooo... Big Thanks.

**Comment by LionZXY** [comment]
PERFECT UNSTABLE HAMMER TEXTURE :))))
