### ISSUE TITLE
Gregtech Blood ASP Crash

### ISSUE THREAD

**Issue by jsaggers** [LionZXY/SimplyHammer#28]
Using [Gregtech Blood ASP version](http://forum.industrial-craft.net/index.php?page=Thread&threadID=11488&pageNo=1), Version 1.05 of Simply Hammers, Forge 1614
[Paste Bin](http://pastebin.com/NibK7vbr) of the crash and yes I use optifine, I have also tried it with optifine disabled.

**Comment by jsaggers** [comment]
Any word? would love to use your mod in my gregtech pack but this is holding me back.

**Comment by LionZXY** [comment]
Oh. Ok.

**Comment by jsaggers** [comment]
Thankyou, I love this hammer mod and when I saw it has Gregtech support I was very happy.

**Comment by ghost** [comment]
Confirming the crash with GT5.09.21.

http://pastebin.com/BS8F8eP4

**Comment by LionZXY** [comment]
Try remove ./config/SimplyHammers/
I can't repeat this bug

**Comment by LionZXY** [comment]
Try [this build](https://yadi.sk/d/4zcZBPS0rEBwW)

**Comment by jsaggers** [comment]
I have still had no success, tried deleting configs, Tried the build you posted, still crashes.
Here is a fresh [crash report](http://pastebin.com/gfFfMYEj).

Mods I am using are:
CodeChickenCore 1.0.7.47
NotEnoughItems 1.0.5.118
FastCraft 1.23
IC2 2.2.821-experimental
Gregtech-5.09.21.jar
SimplyHammer-1.0.5.jar

**Comment by shikhtv** [comment]
У меня тоже крашилась сборка с новой версией Gregtech-5.09.21 и SimplyHammer-1.0.5. Удалил текущие настройки SimplyHammer 1.0.5, откатился на версию 1.0.4 - загрузился с новыми настройками и вернул версию 1.0.5 - все работает, но текстуры GTHammers пропали. Скрин:
![2016-04-24_11 17 04](https://cloud.githubusercontent.com/assets/9385335/14765495/6f869952-0a0e-11e6-8325-b0fff24b129d.png)

**Comment by LionZXY** [comment]
My videocard is broken. I haven't money for repair. I asked a friend fix bug. Please, wait some time.

**Comment by ghost** [comment]
In case anyone else reads this, shikhtv says that version 1.0.4 of simplyhammers works however the ingame model does not show.
