### ISSUE TITLE
Изменение крафта

### ISSUE THREAD

**Issue by LionZXY** [LionZXY/SimplyHammer#6]
Изменение крафта молота. Добавление каменных палочек.

**Comment by LionZXY** [comment]
Изменил крафт. Жду текстуру палочек

**Comment by Dark32** [comment]
Никит, возьми у ментя, не думаю, что Никита обидится на это.

**Comment by LionZXY** [comment]
Ок

**Comment by LionZXY** [comment]
Ан нет. Не нравятся мне они

**Comment by Dark32** [comment]
Ах... ну да, их же я делал, а не Никита. Блин... я сам делал текстуры, Ужас!
