### ISSUE TITLE
[Предложение] Молоты с энергопотреблением...

### ISSUE THREAD

**Issue by Tsyklop** [LionZXY/SimplyHammer#7]
Предлагаю сделать молоты(желательно все) что бы они потребляли RF энергию для своей работы а не были с Уроном.

**Comment by Dark32** [comment]
Перевод: сделать апгрей батарейку, чтобы вместо прочности расходовался заряд.

**Comment by Tsyklop** [comment]
@Dark32 нет...Вообще изначально что бы молоты были на RF энергии а не ещё апгрейды какие-то...

**Comment by LionZXY** [comment]
Будет отдельный рф-молот и еу молот.

**Comment by Tsyklop** [comment]
@LionZXY тогда толку от этого нет...

**Comment by Dark32** [comment]
@Tsyklop, а если в сборке нет RF и EU, то смысл от молотков, если они все на энергии? Лично я категорически против делать все молотки от энергии, апгрейд - куда не шло.

**Comment by Tsyklop** [comment]
@Dark32 кто мешает сделать определение RF в сборке?.никто..

**Comment by Dark32** [comment]
@Tsyklop, это просто глупо и дисбалансно делать все молотки на энергии.
К тому же проблема уже закрыта и дальнейшее обсуждение не больше чем флейм

**Comment by Tsyklop** [comment]
@Dark32 понятное дело...Нуу я считаю что наоборот не дезбалансно так как игрок тратит энергию а не Дурабилити предмета...

**Comment by Dark32** [comment]
@Tsyklop, мы с Никитой уже обсуждали, что прочность можно затолкать в NBT, а мету использовать для молотков, но пока такое не надо.

И вообще, у тебя дома много молотков с батарейками?

**Comment by Tsyklop** [comment]
@Dark32 эмн. нет но у меня дом не из кубов, у меня нет кирок, у меня не стоит реактор или дробитель...У меня дома не бегают всякие магические мобы...Ты не сравнивай реальность с майном...Реальность это реальность а майн это игра...

**Comment by LionZXY** [comment]
Это мой мод. Ни будет ни электрического апгрейда, ни все молоты на энергии. Никаких адекватных аргументов я не услышал, а вот дисбалансных дыр это решение приносит дофига.
