### ISSUE TITLE
Изменить логику Trash апгрейда.

### ISSUE THREAD

**Issue by Dark32** [LionZXY/SimplyHammer#8]
Запретить уничтожать предметы в крафте не являющиеся материалом починки.
Не хорошо чинить молот ведром.

**Comment by LionZXY** [comment]
Хм... Онто не чиниться, но тратиться. Постараюсь сделать

**Comment by LionZXY** [comment]
Не буду делать. Ибо нефиг. Не хочу ради минутной глупости игрока пилить полную поддержку NEi со своим гуи и обработчиком
